# Generated by Django 6.0.6 on 2026-06-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
