# Generated by Django 6.0.6 on 2026-06-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_banners/'),
        ),
    ]
